/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fabi3
 */
public class ImpactSummaryScreen extends javax.swing.JFrame {

    /**
     * Creates new form ImpactSummaryScreen
     */
    public ImpactSummaryScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTotalPledgesTitle = new javax.swing.JLabel();
        lblTotalPledgesValue = new javax.swing.JLabel();
        lblPlasticReducedTitle = new javax.swing.JLabel();
        lblPlasticReducedValue = new javax.swing.JLabel();
        lblImpactSummaryTitle = new javax.swing.JLabel();
        lblResourcesTitle = new javax.swing.JLabel();
        scrollImpactSummary = new javax.swing.JScrollPane();
        txtImpactSummary = new javax.swing.JTextArea();
        scrollLocalResources = new javax.swing.JScrollPane();
        txtLocalResources = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Your Impact & Next Steps");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnBack.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTotalPledgesTitle.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTotalPledgesTitle.setText("Total Pledges:");

        lblTotalPledgesValue.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTotalPledgesValue.setText("0");

        lblPlasticReducedTitle.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblPlasticReducedTitle.setText("Estimated plastic reduced (kg):");

        lblPlasticReducedValue.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblPlasticReducedValue.setText("0.0");

        lblImpactSummaryTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblImpactSummaryTitle.setText("Impact Summary");

        lblResourcesTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblResourcesTitle.setText("Local Resources & Next Steps");

        txtImpactSummary.setEditable(false);
        txtImpactSummary.setColumns(20);
        txtImpactSummary.setLineWrap(true);
        txtImpactSummary.setRows(5);
        txtImpactSummary.setText("As pledges are added, your overall impact will appear here.\n\nExample:\n\n• 12 learners have made a pledge.\n• Together, they are preventing an estimated 4.3 kg of plastic from entering the ocean.\n\n");
        txtImpactSummary.setWrapStyleWord(true);
        txtImpactSummary.setMargin(new java.awt.Insets(5, 5, 5, 5));
        scrollImpactSummary.setViewportView(txtImpactSummary);

        txtLocalResources.setEditable(false);
        txtLocalResources.setColumns(20);
        txtLocalResources.setLineWrap(true);
        txtLocalResources.setRows(5);
        txtLocalResources.setText("• Join a local beach or river clean-up.\n\n• Visit nearby enviromental NGOs.\n\n• Start a plastic-free challenge with friends.\n\n• Share this app to inspire others to take action");
        txtLocalResources.setWrapStyleWord(true);
        txtLocalResources.setMargin(new java.awt.Insets(5, 5, 5, 5));
        scrollLocalResources.setViewportView(txtLocalResources);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlasticReducedTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlasticReducedValue))
                            .addComponent(lblImpactSummaryTitle)
                            .addComponent(scrollImpactSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalPledgesTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPledgesValue))
                            .addComponent(scrollLocalResources, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResourcesTitle))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPledgesTitle)
                    .addComponent(lblTotalPledgesValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlasticReducedTitle)
                    .addComponent(lblPlasticReducedValue))
                .addGap(46, 46, 46)
                .addComponent(lblImpactSummaryTitle)
                .addGap(18, 18, 18)
                .addComponent(scrollImpactSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblResourcesTitle)
                .addGap(18, 18, 18)
                .addComponent(scrollLocalResources, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ActionCentreMain mainScreen = new ActionCentreMain();
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpactSummaryScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblImpactSummaryTitle;
    private javax.swing.JLabel lblPlasticReducedTitle;
    private javax.swing.JLabel lblPlasticReducedValue;
    private javax.swing.JLabel lblResourcesTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalPledgesTitle;
    private javax.swing.JLabel lblTotalPledgesValue;
    private javax.swing.JScrollPane scrollImpactSummary;
    private javax.swing.JScrollPane scrollLocalResources;
    private javax.swing.JTextArea txtImpactSummary;
    private javax.swing.JTextArea txtLocalResources;
    // End of variables declaration//GEN-END:variables
}
