/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oceanapp;

import java.awt.CardLayout;

/**
 *
 * @author zacca
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    CardLayout cardLayout;
    public MainFrame() {
        initComponents();
        cardLayout = (CardLayout) cardPanel.getLayout();

    btnHome.addActionListener(e -> cardLayout.show(cardPanel, "homePanel"));
    btnQuiz.addActionListener(e -> cardLayout.show(cardPanel, "quizPanel"));
    btnSummary.addActionListener(e -> cardLayout.show(cardPanel, "summaryPanel"));
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        btnSummary = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        lblTitljLabel = new javax.swing.JLabel();
        homeContentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taIntro = new javax.swing.JTextArea();
        lblHeroImage = new javax.swing.JLabel();
        homeBtnPanel = new javax.swing.JPanel();
        btnStartQuiz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        quizPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Life Below Water - Knowledge & Assessment");
        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));

        navPanel.setPreferredSize(new java.awt.Dimension(180, 291));
        navPanel.setLayout(new java.awt.GridLayout(0, 1));

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHome.setText("Home");
        navPanel.add(btnHome);

        btnQuiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuiz.setText("Knowledge & Assessment (Quiz)");
        navPanel.add(btnQuiz);

        btnSummary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSummary.setText("View Quiz Summary");
        navPanel.add(btnSummary);

        getContentPane().add(navPanel, java.awt.BorderLayout.LINE_START);

        cardPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new java.awt.BorderLayout());

        lblTitljLabel.setText("Home — Intro");
        homePanel.add(lblTitljLabel, java.awt.BorderLayout.CENTER);

        homeContentPanel.setLayout(new java.awt.GridLayout(1, 2));

        taIntro.setEditable(false);
        taIntro.setColumns(20);
        taIntro.setLineWrap(true);
        taIntro.setRows(5);
        taIntro.setText("Welcome! This mini-module helps you learn about marine threats and track your quiz progress over time.\nClick Start Quiz to begin a short assessment — you'll get immediate feedback after each question.\n");
        taIntro.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taIntro);

        homeContentPanel.add(jScrollPane2);

        lblHeroImage.setText("Image Placeholder");
        homeContentPanel.add(lblHeroImage);

        homePanel.add(homeContentPanel, java.awt.BorderLayout.CENTER);

        btnStartQuiz.setText("Start Quiz");
        btnStartQuiz.setPreferredSize(new java.awt.Dimension(140, 36));
        btnStartQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartQuizActionPerformed(evt);
            }
        });
        homeBtnPanel.add(btnStartQuiz);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("sasaasz<sx<as");
        jScrollPane1.setViewportView(jTextArea1);

        homeBtnPanel.add(jScrollPane1);

        homePanel.add(homeBtnPanel, java.awt.BorderLayout.SOUTH);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Life Below Water — Knowledge & Assessment");
        lblTitle.setToolTipText("");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        homePanel.add(lblTitle, java.awt.BorderLayout.NORTH);

        cardPanel.add(homePanel, "card2");

        jLabel2.setText("Quiz — Welcome");

        javax.swing.GroupLayout quizPanelLayout = new javax.swing.GroupLayout(quizPanel);
        quizPanel.setLayout(quizPanelLayout);
        quizPanelLayout.setHorizontalGroup(
            quizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        quizPanelLayout.setVerticalGroup(
            quizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        cardPanel.add(quizPanel, "card3");

        jLabel3.setText("Summary — Past Attempts");

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        cardPanel.add(summaryPanel, "card4");

        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartQuizActionPerformed
        // TODO add your handling code here:
          cardLayout.show(cardPanel, "quizPanel");
    }//GEN-LAST:event_btnStartQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JButton btnStartQuiz;
    private javax.swing.JButton btnSummary;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel homeBtnPanel;
    private javax.swing.JPanel homeContentPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblHeroImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitljLabel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel quizPanel;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JTextArea taIntro;
    // End of variables declaration//GEN-END:variables
}
